[package]
name = "superdo"
version = "0.2.0"
authors = ["fengyingcai <fengyc.work@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
env_logger = "0.7"