name: "PreRelease"

on:
  push:
    tags:
      - "v*"

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Build
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      # Upload artifact
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: superdo
          path: target/release/superdo

      # Development Release
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          draft: true
          files: |
            target/release/superdo
